// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Ionoscloud.Pulumi.Ionoscloud.Objectstoragemanagement
{
    /// <summary>
    /// Manages an [Object Storage Accesskey](https://docs.ionos.com/cloud/storage-and-backup/ionos-object-storage/concepts/key-management) on IonosCloud.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Ionoscloud = Ionoscloud.Pulumi.Ionoscloud;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new Ionoscloud.Objectstoragemanagement.Accesskey("example", new()
    ///     {
    ///         Description = "my description",
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// An object storage accesskey resource can be imported using its `resource id`, e.g.
    /// 
    /// ```sh
    /// $ pulumi import ionoscloud:objectstoragemanagement/accesskey:Accesskey demo objectStorageAccesskeyid
    /// ```
    /// 
    /// This can be helpful when you want to import Object Storage Accesskeys which you have already created manually or using other means, outside of terraform.
    /// </summary>
    [IonoscloudResourceType("ionoscloud:objectstoragemanagement/accesskey:Accesskey")]
    public partial class Accesskey : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Access key metadata is a string of 92 characters.
        /// </summary>
        [Output("accesskey")]
        public Output<string> Accesskey { get; private set; } = null!;

        /// <summary>
        /// The canonical user ID which is valid for user-owned buckets.
        /// </summary>
        [Output("canonicalUserId")]
        public Output<string> CanonicalUserId { get; private set; } = null!;

        /// <summary>
        /// The contract user ID which is valid for contract-owned buckets
        /// </summary>
        [Output("contractUserId")]
        public Output<string> ContractUserId { get; private set; } = null!;

        /// <summary>
        /// [string] Description of the Access key.
        /// </summary>
        [Output("description")]
        public Output<string> Description { get; private set; } = null!;

        /// <summary>
        /// The secret key of the Access key.
        /// </summary>
        [Output("secretkey")]
        public Output<string> Secretkey { get; private set; } = null!;

        /// <summary>
        /// Timeouts for this resource.
        /// </summary>
        [Output("timeouts")]
        public Output<Outputs.AccesskeyTimeouts?> Timeouts { get; private set; } = null!;


        /// <summary>
        /// Create a Accesskey resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Accesskey(string name, AccesskeyArgs? args = null, CustomResourceOptions? options = null)
            : base("ionoscloud:objectstoragemanagement/accesskey:Accesskey", name, args ?? new AccesskeyArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Accesskey(string name, Input<string> id, AccesskeyState? state = null, CustomResourceOptions? options = null)
            : base("ionoscloud:objectstoragemanagement/accesskey:Accesskey", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/ionos-cloud",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Accesskey resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Accesskey Get(string name, Input<string> id, AccesskeyState? state = null, CustomResourceOptions? options = null)
        {
            return new Accesskey(name, id, state, options);
        }
    }

    public sealed class AccesskeyArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// [string] Description of the Access key.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Timeouts for this resource.
        /// </summary>
        [Input("timeouts")]
        public Input<Inputs.AccesskeyTimeoutsArgs>? Timeouts { get; set; }

        public AccesskeyArgs()
        {
        }
        public static new AccesskeyArgs Empty => new AccesskeyArgs();
    }

    public sealed class AccesskeyState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Access key metadata is a string of 92 characters.
        /// </summary>
        [Input("accesskey")]
        public Input<string>? Accesskey { get; set; }

        /// <summary>
        /// The canonical user ID which is valid for user-owned buckets.
        /// </summary>
        [Input("canonicalUserId")]
        public Input<string>? CanonicalUserId { get; set; }

        /// <summary>
        /// The contract user ID which is valid for contract-owned buckets
        /// </summary>
        [Input("contractUserId")]
        public Input<string>? ContractUserId { get; set; }

        /// <summary>
        /// [string] Description of the Access key.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The secret key of the Access key.
        /// </summary>
        [Input("secretkey")]
        public Input<string>? Secretkey { get; set; }

        /// <summary>
        /// Timeouts for this resource.
        /// </summary>
        [Input("timeouts")]
        public Input<Inputs.AccesskeyTimeoutsGetArgs>? Timeouts { get; set; }

        public AccesskeyState()
        {
        }
        public static new AccesskeyState Empty => new AccesskeyState();
    }
}
