// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.ionoscloud.nfs.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ShareClientGroupNfs {
    /**
     * @return The squash mode for the export. The squash mode can be:
     * 
     */
    private @Nullable String squash;

    private ShareClientGroupNfs() {}
    /**
     * @return The squash mode for the export. The squash mode can be:
     * 
     */
    public Optional<String> squash() {
        return Optional.ofNullable(this.squash);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ShareClientGroupNfs defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String squash;
        public Builder() {}
        public Builder(ShareClientGroupNfs defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.squash = defaults.squash;
        }

        @CustomType.Setter
        public Builder squash(@Nullable String squash) {

            this.squash = squash;
            return this;
        }
        public ShareClientGroupNfs build() {
            final var _resultValue = new ShareClientGroupNfs();
            _resultValue.squash = squash;
            return _resultValue;
        }
    }
}
