// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.ionoscloud.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.List;
import java.util.Objects;


public final class ContainerRegistryTokenScopeArgs extends com.pulumi.resources.ResourceArgs {

    public static final ContainerRegistryTokenScopeArgs Empty = new ContainerRegistryTokenScopeArgs();

    /**
     * [string] Example: [&#34;pull&#34;, &#34;push&#34;, &#34;delete&#34;]
     * 
     */
    @Import(name="actions", required=true)
    private Output<List<String>> actions;

    /**
     * @return [string] Example: [&#34;pull&#34;, &#34;push&#34;, &#34;delete&#34;]
     * 
     */
    public Output<List<String>> actions() {
        return this.actions;
    }

    /**
     * [string]
     * 
     */
    @Import(name="name", required=true)
    private Output<String> name;

    /**
     * @return [string]
     * 
     */
    public Output<String> name() {
        return this.name;
    }

    /**
     * [string]
     * 
     */
    @Import(name="type", required=true)
    private Output<String> type;

    /**
     * @return [string]
     * 
     */
    public Output<String> type() {
        return this.type;
    }

    private ContainerRegistryTokenScopeArgs() {}

    private ContainerRegistryTokenScopeArgs(ContainerRegistryTokenScopeArgs $) {
        this.actions = $.actions;
        this.name = $.name;
        this.type = $.type;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ContainerRegistryTokenScopeArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ContainerRegistryTokenScopeArgs $;

        public Builder() {
            $ = new ContainerRegistryTokenScopeArgs();
        }

        public Builder(ContainerRegistryTokenScopeArgs defaults) {
            $ = new ContainerRegistryTokenScopeArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param actions [string] Example: [&#34;pull&#34;, &#34;push&#34;, &#34;delete&#34;]
         * 
         * @return builder
         * 
         */
        public Builder actions(Output<List<String>> actions) {
            $.actions = actions;
            return this;
        }

        /**
         * @param actions [string] Example: [&#34;pull&#34;, &#34;push&#34;, &#34;delete&#34;]
         * 
         * @return builder
         * 
         */
        public Builder actions(List<String> actions) {
            return actions(Output.of(actions));
        }

        /**
         * @param actions [string] Example: [&#34;pull&#34;, &#34;push&#34;, &#34;delete&#34;]
         * 
         * @return builder
         * 
         */
        public Builder actions(String... actions) {
            return actions(List.of(actions));
        }

        /**
         * @param name [string]
         * 
         * @return builder
         * 
         */
        public Builder name(Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name [string]
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param type [string]
         * 
         * @return builder
         * 
         */
        public Builder type(Output<String> type) {
            $.type = type;
            return this;
        }

        /**
         * @param type [string]
         * 
         * @return builder
         * 
         */
        public Builder type(String type) {
            return type(Output.of(type));
        }

        public ContainerRegistryTokenScopeArgs build() {
            if ($.actions == null) {
                throw new MissingRequiredPropertyException("ContainerRegistryTokenScopeArgs", "actions");
            }
            if ($.name == null) {
                throw new MissingRequiredPropertyException("ContainerRegistryTokenScopeArgs", "name");
            }
            if ($.type == null) {
                throw new MissingRequiredPropertyException("ContainerRegistryTokenScopeArgs", "type");
            }
            return $;
        }
    }

}
