// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.ionoscloud.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.ionoscloud.inputs.GetServersFilterArgs;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetServersArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetServersArgs Empty = new GetServersArgs();

    /**
     * Name of an existing datacenter that the servers are a part of
     * 
     */
    @Import(name="datacenterId", required=true)
    private Output<String> datacenterId;

    /**
     * @return Name of an existing datacenter that the servers are a part of
     * 
     */
    public Output<String> datacenterId() {
        return this.datacenterId;
    }

    /**
     * One or more name/value pairs to filter off of. You can use most base fields in the server resource. These do **NOT** include nested fields in nics or volume nested fields.
     * 
     * `datacenter_id` must be provided. If `datacenter_id` is missing , the datasource will return an error.
     * 
     * **NOTE:** Lookup by filter is partial. Searching for a server using filter name and value `test`, will find all servers that have `test` in the name.
     * For example, it will find servers named `test`, `test1`, `testsomething`.
     * 
     * **NOTE:** You cannot search by `image_name` by providing an alias like `ubuntu`.
     * 
     */
    @Import(name="filters")
    private @Nullable Output<List<GetServersFilterArgs>> filters;

    /**
     * @return One or more name/value pairs to filter off of. You can use most base fields in the server resource. These do **NOT** include nested fields in nics or volume nested fields.
     * 
     * `datacenter_id` must be provided. If `datacenter_id` is missing , the datasource will return an error.
     * 
     * **NOTE:** Lookup by filter is partial. Searching for a server using filter name and value `test`, will find all servers that have `test` in the name.
     * For example, it will find servers named `test`, `test1`, `testsomething`.
     * 
     * **NOTE:** You cannot search by `image_name` by providing an alias like `ubuntu`.
     * 
     */
    public Optional<Output<List<GetServersFilterArgs>>> filters() {
        return Optional.ofNullable(this.filters);
    }

    private GetServersArgs() {}

    private GetServersArgs(GetServersArgs $) {
        this.datacenterId = $.datacenterId;
        this.filters = $.filters;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetServersArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetServersArgs $;

        public Builder() {
            $ = new GetServersArgs();
        }

        public Builder(GetServersArgs defaults) {
            $ = new GetServersArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param datacenterId Name of an existing datacenter that the servers are a part of
         * 
         * @return builder
         * 
         */
        public Builder datacenterId(Output<String> datacenterId) {
            $.datacenterId = datacenterId;
            return this;
        }

        /**
         * @param datacenterId Name of an existing datacenter that the servers are a part of
         * 
         * @return builder
         * 
         */
        public Builder datacenterId(String datacenterId) {
            return datacenterId(Output.of(datacenterId));
        }

        /**
         * @param filters One or more name/value pairs to filter off of. You can use most base fields in the server resource. These do **NOT** include nested fields in nics or volume nested fields.
         * 
         * `datacenter_id` must be provided. If `datacenter_id` is missing , the datasource will return an error.
         * 
         * **NOTE:** Lookup by filter is partial. Searching for a server using filter name and value `test`, will find all servers that have `test` in the name.
         * For example, it will find servers named `test`, `test1`, `testsomething`.
         * 
         * **NOTE:** You cannot search by `image_name` by providing an alias like `ubuntu`.
         * 
         * @return builder
         * 
         */
        public Builder filters(@Nullable Output<List<GetServersFilterArgs>> filters) {
            $.filters = filters;
            return this;
        }

        /**
         * @param filters One or more name/value pairs to filter off of. You can use most base fields in the server resource. These do **NOT** include nested fields in nics or volume nested fields.
         * 
         * `datacenter_id` must be provided. If `datacenter_id` is missing , the datasource will return an error.
         * 
         * **NOTE:** Lookup by filter is partial. Searching for a server using filter name and value `test`, will find all servers that have `test` in the name.
         * For example, it will find servers named `test`, `test1`, `testsomething`.
         * 
         * **NOTE:** You cannot search by `image_name` by providing an alias like `ubuntu`.
         * 
         * @return builder
         * 
         */
        public Builder filters(List<GetServersFilterArgs> filters) {
            return filters(Output.of(filters));
        }

        /**
         * @param filters One or more name/value pairs to filter off of. You can use most base fields in the server resource. These do **NOT** include nested fields in nics or volume nested fields.
         * 
         * `datacenter_id` must be provided. If `datacenter_id` is missing , the datasource will return an error.
         * 
         * **NOTE:** Lookup by filter is partial. Searching for a server using filter name and value `test`, will find all servers that have `test` in the name.
         * For example, it will find servers named `test`, `test1`, `testsomething`.
         * 
         * **NOTE:** You cannot search by `image_name` by providing an alias like `ubuntu`.
         * 
         * @return builder
         * 
         */
        public Builder filters(GetServersFilterArgs... filters) {
            return filters(List.of(filters));
        }

        public GetServersArgs build() {
            if ($.datacenterId == null) {
                throw new MissingRequiredPropertyException("GetServersArgs", "datacenterId");
            }
            return $;
        }
    }

}
