// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ionoscloud.pulumi.ionoscloud.objectstorage.inputs;

import com.ionoscloud.pulumi.ionoscloud.objectstorage.inputs.BucketLifecycleConfigurationRuleAbortIncompleteMultipartUploadArgs;
import com.ionoscloud.pulumi.ionoscloud.objectstorage.inputs.BucketLifecycleConfigurationRuleExpirationArgs;
import com.ionoscloud.pulumi.ionoscloud.objectstorage.inputs.BucketLifecycleConfigurationRuleFilterArgs;
import com.ionoscloud.pulumi.ionoscloud.objectstorage.inputs.BucketLifecycleConfigurationRuleNoncurrentVersionExpirationArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class BucketLifecycleConfigurationRuleArgs extends com.pulumi.resources.ResourceArgs {

    public static final BucketLifecycleConfigurationRuleArgs Empty = new BucketLifecycleConfigurationRuleArgs();

    /**
     * Specifies the days since the initiation of an incomplete multipart upload that IONOS Object Storage Object Storage will wait before permanently removing all parts of the upload.
     * 
     */
    @Import(name="abortIncompleteMultipartUpload")
    private @Nullable Output<BucketLifecycleConfigurationRuleAbortIncompleteMultipartUploadArgs> abortIncompleteMultipartUpload;

    /**
     * @return Specifies the days since the initiation of an incomplete multipart upload that IONOS Object Storage Object Storage will wait before permanently removing all parts of the upload.
     * 
     */
    public Optional<Output<BucketLifecycleConfigurationRuleAbortIncompleteMultipartUploadArgs>> abortIncompleteMultipartUpload() {
        return Optional.ofNullable(this.abortIncompleteMultipartUpload);
    }

    /**
     * A lifecycle rule for when an object expires.
     * 
     */
    @Import(name="expiration")
    private @Nullable Output<BucketLifecycleConfigurationRuleExpirationArgs> expiration;

    /**
     * @return A lifecycle rule for when an object expires.
     * 
     */
    public Optional<Output<BucketLifecycleConfigurationRuleExpirationArgs>> expiration() {
        return Optional.ofNullable(this.expiration);
    }

    /**
     * A filter.
     * 
     */
    @Import(name="filter")
    private @Nullable Output<BucketLifecycleConfigurationRuleFilterArgs> filter;

    /**
     * @return A filter.
     * 
     */
    public Optional<Output<BucketLifecycleConfigurationRuleFilterArgs>> filter() {
        return Optional.ofNullable(this.filter);
    }

    /**
     * Unique identifier for the rule.
     * 
     */
    @Import(name="id")
    private @Nullable Output<String> id;

    /**
     * @return Unique identifier for the rule.
     * 
     */
    public Optional<Output<String>> id() {
        return Optional.ofNullable(this.id);
    }

    /**
     * A lifecycle rule for when non-current object versions expire.
     * 
     */
    @Import(name="noncurrentVersionExpiration")
    private @Nullable Output<BucketLifecycleConfigurationRuleNoncurrentVersionExpirationArgs> noncurrentVersionExpiration;

    /**
     * @return A lifecycle rule for when non-current object versions expire.
     * 
     */
    public Optional<Output<BucketLifecycleConfigurationRuleNoncurrentVersionExpirationArgs>> noncurrentVersionExpiration() {
        return Optional.ofNullable(this.noncurrentVersionExpiration);
    }

    /**
     * Object key prefix identifying one or more objects to which the rule applies.
     * 
     * @deprecated
     * This field is deprecated and will be removed in a future version. It does nothing. Use &#39;filter&#39; block instead.
     * 
     */
    @Deprecated /* This field is deprecated and will be removed in a future version. It does nothing. Use 'filter' block instead. */
    @Import(name="prefix")
    private @Nullable Output<String> prefix;

    /**
     * @return Object key prefix identifying one or more objects to which the rule applies.
     * 
     * @deprecated
     * This field is deprecated and will be removed in a future version. It does nothing. Use &#39;filter&#39; block instead.
     * 
     */
    @Deprecated /* This field is deprecated and will be removed in a future version. It does nothing. Use 'filter' block instead. */
    public Optional<Output<String>> prefix() {
        return Optional.ofNullable(this.prefix);
    }

    /**
     * Whether the rule is currently being applied. Valid values: Enabled or Disabled.
     * 
     */
    @Import(name="status", required=true)
    private Output<String> status;

    /**
     * @return Whether the rule is currently being applied. Valid values: Enabled or Disabled.
     * 
     */
    public Output<String> status() {
        return this.status;
    }

    private BucketLifecycleConfigurationRuleArgs() {}

    private BucketLifecycleConfigurationRuleArgs(BucketLifecycleConfigurationRuleArgs $) {
        this.abortIncompleteMultipartUpload = $.abortIncompleteMultipartUpload;
        this.expiration = $.expiration;
        this.filter = $.filter;
        this.id = $.id;
        this.noncurrentVersionExpiration = $.noncurrentVersionExpiration;
        this.prefix = $.prefix;
        this.status = $.status;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(BucketLifecycleConfigurationRuleArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private BucketLifecycleConfigurationRuleArgs $;

        public Builder() {
            $ = new BucketLifecycleConfigurationRuleArgs();
        }

        public Builder(BucketLifecycleConfigurationRuleArgs defaults) {
            $ = new BucketLifecycleConfigurationRuleArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param abortIncompleteMultipartUpload Specifies the days since the initiation of an incomplete multipart upload that IONOS Object Storage Object Storage will wait before permanently removing all parts of the upload.
         * 
         * @return builder
         * 
         */
        public Builder abortIncompleteMultipartUpload(@Nullable Output<BucketLifecycleConfigurationRuleAbortIncompleteMultipartUploadArgs> abortIncompleteMultipartUpload) {
            $.abortIncompleteMultipartUpload = abortIncompleteMultipartUpload;
            return this;
        }

        /**
         * @param abortIncompleteMultipartUpload Specifies the days since the initiation of an incomplete multipart upload that IONOS Object Storage Object Storage will wait before permanently removing all parts of the upload.
         * 
         * @return builder
         * 
         */
        public Builder abortIncompleteMultipartUpload(BucketLifecycleConfigurationRuleAbortIncompleteMultipartUploadArgs abortIncompleteMultipartUpload) {
            return abortIncompleteMultipartUpload(Output.of(abortIncompleteMultipartUpload));
        }

        /**
         * @param expiration A lifecycle rule for when an object expires.
         * 
         * @return builder
         * 
         */
        public Builder expiration(@Nullable Output<BucketLifecycleConfigurationRuleExpirationArgs> expiration) {
            $.expiration = expiration;
            return this;
        }

        /**
         * @param expiration A lifecycle rule for when an object expires.
         * 
         * @return builder
         * 
         */
        public Builder expiration(BucketLifecycleConfigurationRuleExpirationArgs expiration) {
            return expiration(Output.of(expiration));
        }

        /**
         * @param filter A filter.
         * 
         * @return builder
         * 
         */
        public Builder filter(@Nullable Output<BucketLifecycleConfigurationRuleFilterArgs> filter) {
            $.filter = filter;
            return this;
        }

        /**
         * @param filter A filter.
         * 
         * @return builder
         * 
         */
        public Builder filter(BucketLifecycleConfigurationRuleFilterArgs filter) {
            return filter(Output.of(filter));
        }

        /**
         * @param id Unique identifier for the rule.
         * 
         * @return builder
         * 
         */
        public Builder id(@Nullable Output<String> id) {
            $.id = id;
            return this;
        }

        /**
         * @param id Unique identifier for the rule.
         * 
         * @return builder
         * 
         */
        public Builder id(String id) {
            return id(Output.of(id));
        }

        /**
         * @param noncurrentVersionExpiration A lifecycle rule for when non-current object versions expire.
         * 
         * @return builder
         * 
         */
        public Builder noncurrentVersionExpiration(@Nullable Output<BucketLifecycleConfigurationRuleNoncurrentVersionExpirationArgs> noncurrentVersionExpiration) {
            $.noncurrentVersionExpiration = noncurrentVersionExpiration;
            return this;
        }

        /**
         * @param noncurrentVersionExpiration A lifecycle rule for when non-current object versions expire.
         * 
         * @return builder
         * 
         */
        public Builder noncurrentVersionExpiration(BucketLifecycleConfigurationRuleNoncurrentVersionExpirationArgs noncurrentVersionExpiration) {
            return noncurrentVersionExpiration(Output.of(noncurrentVersionExpiration));
        }

        /**
         * @param prefix Object key prefix identifying one or more objects to which the rule applies.
         * 
         * @return builder
         * 
         * @deprecated
         * This field is deprecated and will be removed in a future version. It does nothing. Use &#39;filter&#39; block instead.
         * 
         */
        @Deprecated /* This field is deprecated and will be removed in a future version. It does nothing. Use 'filter' block instead. */
        public Builder prefix(@Nullable Output<String> prefix) {
            $.prefix = prefix;
            return this;
        }

        /**
         * @param prefix Object key prefix identifying one or more objects to which the rule applies.
         * 
         * @return builder
         * 
         * @deprecated
         * This field is deprecated and will be removed in a future version. It does nothing. Use &#39;filter&#39; block instead.
         * 
         */
        @Deprecated /* This field is deprecated and will be removed in a future version. It does nothing. Use 'filter' block instead. */
        public Builder prefix(String prefix) {
            return prefix(Output.of(prefix));
        }

        /**
         * @param status Whether the rule is currently being applied. Valid values: Enabled or Disabled.
         * 
         * @return builder
         * 
         */
        public Builder status(Output<String> status) {
            $.status = status;
            return this;
        }

        /**
         * @param status Whether the rule is currently being applied. Valid values: Enabled or Disabled.
         * 
         * @return builder
         * 
         */
        public Builder status(String status) {
            return status(Output.of(status));
        }

        public BucketLifecycleConfigurationRuleArgs build() {
            if ($.status == null) {
                throw new MissingRequiredPropertyException("BucketLifecycleConfigurationRuleArgs", "status");
            }
            return $;
        }
    }

}
