// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ionoscloud.pulumi.ionoscloud.dbaas.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetMariaDBClustersV2ItemCredentials {
    /**
     * @return The name of the initial database.
     * 
     */
    private String database;
    /**
     * @return The username of the initial MariaDB user.
     * 
     */
    private String username;

    private GetMariaDBClustersV2ItemCredentials() {}
    /**
     * @return The name of the initial database.
     * 
     */
    public String database() {
        return this.database;
    }
    /**
     * @return The username of the initial MariaDB user.
     * 
     */
    public String username() {
        return this.username;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetMariaDBClustersV2ItemCredentials defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String database;
        private String username;
        public Builder() {}
        public Builder(GetMariaDBClustersV2ItemCredentials defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.database = defaults.database;
    	      this.username = defaults.username;
        }

        @CustomType.Setter
        public Builder database(String database) {
            if (database == null) {
              throw new MissingRequiredPropertyException("GetMariaDBClustersV2ItemCredentials", "database");
            }
            this.database = database;
            return this;
        }
        @CustomType.Setter
        public Builder username(String username) {
            if (username == null) {
              throw new MissingRequiredPropertyException("GetMariaDBClustersV2ItemCredentials", "username");
            }
            this.username = username;
            return this;
        }
        public GetMariaDBClustersV2ItemCredentials build() {
            final var _resultValue = new GetMariaDBClustersV2ItemCredentials();
            _resultValue.database = database;
            _resultValue.username = username;
            return _resultValue;
        }
    }
}
