# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = [
    'AutoCertificateProviderExternalAccountBindingArgs',
    'AutoCertificateProviderExternalAccountBindingArgsDict',
]

class AutoCertificateProviderExternalAccountBindingArgsDict(TypedDict):
    key_id: pulumi.Input[_builtins.str]
    """
    [string] The key ID of the external account binding.
    """
    key_secret: pulumi.Input[_builtins.str]
    """
    [string] The key secret of the external account binding
    """

@pulumi.input_type
class AutoCertificateProviderExternalAccountBindingArgs:
    def __init__(__self__, *,
                 key_id: pulumi.Input[_builtins.str],
                 key_secret: pulumi.Input[_builtins.str]):
        """
        :param pulumi.Input[_builtins.str] key_id: [string] The key ID of the external account binding.
        :param pulumi.Input[_builtins.str] key_secret: [string] The key secret of the external account binding
        """
        pulumi.set(__self__, "key_id", key_id)
        pulumi.set(__self__, "key_secret", key_secret)

    @_builtins.property
    @pulumi.getter(name="keyId")
    def key_id(self) -> pulumi.Input[_builtins.str]:
        """
        [string] The key ID of the external account binding.
        """
        return pulumi.get(self, "key_id")

    @key_id.setter
    def key_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "key_id", value)

    @_builtins.property
    @pulumi.getter(name="keySecret")
    def key_secret(self) -> pulumi.Input[_builtins.str]:
        """
        [string] The key secret of the external account binding
        """
        return pulumi.get(self, "key_secret")

    @key_secret.setter
    def key_secret(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "key_secret", value)


