# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs

__all__ = [
    'GetMariaDBBackupLocationsV2Result',
    'AwaitableGetMariaDBBackupLocationsV2Result',
    'get_maria_db_backup_locations_v2',
    'get_maria_db_backup_locations_v2_output',
]

@pulumi.output_type
class GetMariaDBBackupLocationsV2Result:
    """
    A collection of values returned by getMariaDBBackupLocationsV2.
    """
    def __init__(__self__, id=None, items=None, location=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if items and not isinstance(items, list):
            raise TypeError("Expected argument 'items' to be a list")
        pulumi.set(__self__, "items", items)
        if location and not isinstance(location, str):
            raise TypeError("Expected argument 'location' to be a str")
        pulumi.set(__self__, "location", location)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def items(self) -> Sequence['outputs.GetMariaDBBackupLocationsV2ItemResult']:
        """
        List of backup location objects. Each item includes:
        """
        return pulumi.get(self, "items")

    @_builtins.property
    @pulumi.getter
    def location(self) -> _builtins.str:
        """
        The Object Storage location name.
        """
        return pulumi.get(self, "location")


class AwaitableGetMariaDBBackupLocationsV2Result(GetMariaDBBackupLocationsV2Result):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetMariaDBBackupLocationsV2Result(
            id=self.id,
            items=self.items,
            location=self.location)


def get_maria_db_backup_locations_v2(location: Optional[_builtins.str] = None,
                                     opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetMariaDBBackupLocationsV2Result:
    """
    The `dbaas_get_maria_db_backup_locations_v2` data source can be used to retrieve the supported MariaDB V2 backup locations for a given API endpoint.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_ionoscloud as ionoscloud

    example = ionoscloud.dbaas.get_maria_db_backup_locations_v2(location="de/txl")
    ```


    :param _builtins.str location: [string] The location to query. Requests are routed to the corresponding regional MariaDB endpoint. Available locations: `de/fra`, `de/fra/1`, `de/fra/2`, `de/txl`, `es/vit`, `fr/par`, `gb/bhx`, `gb/lhr`, `us/ewr`, `us/las`, `us/mci`.
    """
    __args__ = dict()
    __args__['location'] = location
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('ionoscloud:dbaas/getMariaDBBackupLocationsV2:getMariaDBBackupLocationsV2', __args__, opts=opts, typ=GetMariaDBBackupLocationsV2Result).value

    return AwaitableGetMariaDBBackupLocationsV2Result(
        id=pulumi.get(__ret__, 'id'),
        items=pulumi.get(__ret__, 'items'),
        location=pulumi.get(__ret__, 'location'))
def get_maria_db_backup_locations_v2_output(location: pulumi.Input[Optional[_builtins.str]] = None,
                                            opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetMariaDBBackupLocationsV2Result]:
    """
    The `dbaas_get_maria_db_backup_locations_v2` data source can be used to retrieve the supported MariaDB V2 backup locations for a given API endpoint.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_ionoscloud as ionoscloud

    example = ionoscloud.dbaas.get_maria_db_backup_locations_v2(location="de/txl")
    ```


    :param _builtins.str location: [string] The location to query. Requests are routed to the corresponding regional MariaDB endpoint. Available locations: `de/fra`, `de/fra/1`, `de/fra/2`, `de/txl`, `es/vit`, `fr/par`, `gb/bhx`, `gb/lhr`, `us/ewr`, `us/las`, `us/mci`.
    """
    __args__ = dict()
    __args__['location'] = location
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('ionoscloud:dbaas/getMariaDBBackupLocationsV2:getMariaDBBackupLocationsV2', __args__, opts=opts, typ=GetMariaDBBackupLocationsV2Result)
    return __ret__.apply(lambda __response__: GetMariaDBBackupLocationsV2Result(
        id=pulumi.get(__response__, 'id'),
        items=pulumi.get(__response__, 'items'),
        location=pulumi.get(__response__, 'location')))
