# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs

__all__ = [
    'GetPSQLVersionsV2Result',
    'AwaitableGetPSQLVersionsV2Result',
    'get_psql_versions_v2',
    'get_psql_versions_v2_output',
]

@pulumi.output_type
class GetPSQLVersionsV2Result:
    """
    A collection of values returned by getPSQLVersionsV2.
    """
    def __init__(__self__, id=None, location=None, versions=None):
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if location and not isinstance(location, str):
            raise TypeError("Expected argument 'location' to be a str")
        pulumi.set(__self__, "location", location)
        if versions and not isinstance(versions, list):
            raise TypeError("Expected argument 'versions' to be a list")
        pulumi.set(__self__, "versions", versions)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def location(self) -> _builtins.str:
        return pulumi.get(self, "location")

    @_builtins.property
    @pulumi.getter
    def versions(self) -> Sequence['outputs.GetPSQLVersionsV2VersionResult']:
        """
        The list of available PostgreSQL versions. Each version has the following attributes:
        """
        return pulumi.get(self, "versions")


class AwaitableGetPSQLVersionsV2Result(GetPSQLVersionsV2Result):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetPSQLVersionsV2Result(
            id=self.id,
            location=self.location,
            versions=self.versions)


def get_psql_versions_v2(location: Optional[_builtins.str] = None,
                         opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetPSQLVersionsV2Result:
    """
    The **DBaaS PostgreSQL v2 Versions data source** can be used to retrieve the list of available PostgreSQL versions.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_ionoscloud as ionoscloud

    example = ionoscloud.dbaas.get_psql_versions_v2(location="de/txl")
    ```


    :param _builtins.str location: [string] The region in which to look up available versions. Available locations: `de/fra`, `de/fra/2`, `de/txl`, `es/vit`, `fr/par`, `gb/bhx`, `gb/lhr`, `us/ewr`, `us/las`, `us/mci`.
    """
    __args__ = dict()
    __args__['location'] = location
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('ionoscloud:dbaas/getPSQLVersionsV2:getPSQLVersionsV2', __args__, opts=opts, typ=GetPSQLVersionsV2Result).value

    return AwaitableGetPSQLVersionsV2Result(
        id=pulumi.get(__ret__, 'id'),
        location=pulumi.get(__ret__, 'location'),
        versions=pulumi.get(__ret__, 'versions'))
def get_psql_versions_v2_output(location: pulumi.Input[Optional[_builtins.str]] = None,
                                opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetPSQLVersionsV2Result]:
    """
    The **DBaaS PostgreSQL v2 Versions data source** can be used to retrieve the list of available PostgreSQL versions.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_ionoscloud as ionoscloud

    example = ionoscloud.dbaas.get_psql_versions_v2(location="de/txl")
    ```


    :param _builtins.str location: [string] The region in which to look up available versions. Available locations: `de/fra`, `de/fra/2`, `de/txl`, `es/vit`, `fr/par`, `gb/bhx`, `gb/lhr`, `us/ewr`, `us/las`, `us/mci`.
    """
    __args__ = dict()
    __args__['location'] = location
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('ionoscloud:dbaas/getPSQLVersionsV2:getPSQLVersionsV2', __args__, opts=opts, typ=GetPSQLVersionsV2Result)
    return __ret__.apply(lambda __response__: GetPSQLVersionsV2Result(
        id=pulumi.get(__response__, 'id'),
        location=pulumi.get(__response__, 'location'),
        versions=pulumi.get(__response__, 'versions')))
