// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.ionoscloud.vpn.inputs;

import com.pulumi.core.annotations.Import;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetWireguardGatewayPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetWireguardGatewayPlainArgs Empty = new GetWireguardGatewayPlainArgs();

    /**
     * The description of the WireGuard Gateway.
     * 
     */
    @Import(name="description")
    private @Nullable String description;

    /**
     * @return The description of the WireGuard Gateway.
     * 
     */
    public Optional<String> description() {
        return Optional.ofNullable(this.description);
    }

    /**
     * [String] The ID of the WireGuard Gateway.
     * 
     */
    @Import(name="id")
    private @Nullable String id;

    /**
     * @return [String] The ID of the WireGuard Gateway.
     * 
     */
    public Optional<String> id() {
        return Optional.ofNullable(this.id);
    }

    /**
     * [String] The location of the WireGuard Gateway.
     * 
     */
    @Import(name="location")
    private @Nullable String location;

    /**
     * @return [String] The location of the WireGuard Gateway.
     * 
     */
    public Optional<String> location() {
        return Optional.ofNullable(this.location);
    }

    /**
     * [String] The name of the WireGuard Gateway.
     * 
     */
    @Import(name="name")
    private @Nullable String name;

    /**
     * @return [String] The name of the WireGuard Gateway.
     * 
     */
    public Optional<String> name() {
        return Optional.ofNullable(this.name);
    }

    private GetWireguardGatewayPlainArgs() {}

    private GetWireguardGatewayPlainArgs(GetWireguardGatewayPlainArgs $) {
        this.description = $.description;
        this.id = $.id;
        this.location = $.location;
        this.name = $.name;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetWireguardGatewayPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetWireguardGatewayPlainArgs $;

        public Builder() {
            $ = new GetWireguardGatewayPlainArgs();
        }

        public Builder(GetWireguardGatewayPlainArgs defaults) {
            $ = new GetWireguardGatewayPlainArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param description The description of the WireGuard Gateway.
         * 
         * @return builder
         * 
         */
        public Builder description(@Nullable String description) {
            $.description = description;
            return this;
        }

        /**
         * @param id [String] The ID of the WireGuard Gateway.
         * 
         * @return builder
         * 
         */
        public Builder id(@Nullable String id) {
            $.id = id;
            return this;
        }

        /**
         * @param location [String] The location of the WireGuard Gateway.
         * 
         * @return builder
         * 
         */
        public Builder location(@Nullable String location) {
            $.location = location;
            return this;
        }

        /**
         * @param name [String] The name of the WireGuard Gateway.
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable String name) {
            $.name = name;
            return this;
        }

        public GetWireguardGatewayPlainArgs build() {
            return $;
        }
    }

}
