// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Ionoscloud.Pulumi.Ionoscloud.Dbaas.Outputs
{

    [OutputType]
    public sealed class GetInMemoryDBReplicaSetConnectionResult
    {
        /// <summary>
        /// [string] The IP and subnet for your instance. Note the following unavailable IP ranges: 10.233.64.0/18, 10.233.0.0/18, 10.233.114.0/24.
        /// </summary>
        public readonly string Cidr;
        /// <summary>
        /// [string] The datacenter to connect your instance to.
        /// </summary>
        public readonly string DatacenterId;
        /// <summary>
        /// [string] The numeric LAN ID to connect your instance to.
        /// </summary>
        public readonly string LanId;

        [OutputConstructor]
        private GetInMemoryDBReplicaSetConnectionResult(
            string cidr,

            string datacenterId,

            string lanId)
        {
            Cidr = cidr;
            DatacenterId = datacenterId;
            LanId = lanId;
        }
    }
}
