// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export function getForwardingRule(args: GetForwardingRuleArgs, opts?: pulumi.InvokeOptions): Promise<GetForwardingRuleResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("ionoscloud:nlb/getForwardingRule:getForwardingRule", {
        "datacenterId": args.datacenterId,
        "id": args.id,
        "name": args.name,
        "networkloadbalancerId": args.networkloadbalancerId,
    }, opts);
}

/**
 * A collection of arguments for invoking getForwardingRule.
 */
export interface GetForwardingRuleArgs {
    datacenterId: string;
    id?: string;
    name?: string;
    networkloadbalancerId: string;
}

/**
 * A collection of values returned by getForwardingRule.
 */
export interface GetForwardingRuleResult {
    readonly algorithm: string;
    readonly datacenterId: string;
    readonly healthChecks: outputs.nlb.GetForwardingRuleHealthCheck[];
    readonly id: string;
    readonly listenerIp: string;
    readonly listenerPort: number;
    readonly name: string;
    readonly networkloadbalancerId: string;
    readonly protocol: string;
    readonly targets: outputs.nlb.GetForwardingRuleTarget[];
}
export function getForwardingRuleOutput(args: GetForwardingRuleOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetForwardingRuleResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("ionoscloud:nlb/getForwardingRule:getForwardingRule", {
        "datacenterId": args.datacenterId,
        "id": args.id,
        "name": args.name,
        "networkloadbalancerId": args.networkloadbalancerId,
    }, opts);
}

/**
 * A collection of arguments for invoking getForwardingRule.
 */
export interface GetForwardingRuleOutputArgs {
    datacenterId: pulumi.Input<string>;
    id?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    networkloadbalancerId: pulumi.Input<string>;
}
