// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ionoscloud.Outputs
{

    [OutputType]
    public sealed class VpnWireguardPeerEndpoint
    {
        /// <summary>
        /// [string] The hostname or IPV4 address that the WireGuard Server will connect to.
        /// </summary>
        public readonly string Host;
        /// <summary>
        /// [int] The port that the WireGuard Server will connect to. Defaults to `51820`.
        /// </summary>
        public readonly int? Port;

        [OutputConstructor]
        private VpnWireguardPeerEndpoint(
            string host,

            int? port)
        {
            Host = host;
            Port = port;
        }
    }
}
