// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.ionoscloud.pulumi.ionoscloud.dbaas.inputs;

import com.ionoscloud.pulumi.ionoscloud.dbaas.inputs.PSQLClusterConnectionPoolerArgs;
import com.ionoscloud.pulumi.ionoscloud.dbaas.inputs.PSQLClusterConnectionsArgs;
import com.ionoscloud.pulumi.ionoscloud.dbaas.inputs.PSQLClusterCredentialsArgs;
import com.ionoscloud.pulumi.ionoscloud.dbaas.inputs.PSQLClusterFromBackupArgs;
import com.ionoscloud.pulumi.ionoscloud.dbaas.inputs.PSQLClusterMaintenanceWindowArgs;
import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class PSQLClusterState extends com.pulumi.resources.ResourceArgs {

    public static final PSQLClusterState Empty = new PSQLClusterState();

    /**
     * (Computed)[string] The IONOS Object Storage location where the backups will be stored. Possible values are: `de`, `eu-south-2`, `eu-central-2`. This attribute is immutable (disallowed in update requests).
     * 
     */
    @Import(name="backupLocation")
    private @Nullable Output<String> backupLocation;

    /**
     * @return (Computed)[string] The IONOS Object Storage location where the backups will be stored. Possible values are: `de`, `eu-south-2`, `eu-central-2`. This attribute is immutable (disallowed in update requests).
     * 
     */
    public Optional<Output<String>> backupLocation() {
        return Optional.ofNullable(this.backupLocation);
    }

    /**
     * [object]
     * 
     */
    @Import(name="connectionPooler")
    private @Nullable Output<PSQLClusterConnectionPoolerArgs> connectionPooler;

    /**
     * @return [object]
     * 
     */
    public Optional<Output<PSQLClusterConnectionPoolerArgs>> connectionPooler() {
        return Optional.ofNullable(this.connectionPooler);
    }

    /**
     * [string] Details about the network connection for your cluster.
     * 
     */
    @Import(name="connections")
    private @Nullable Output<PSQLClusterConnectionsArgs> connections;

    /**
     * @return [string] Details about the network connection for your cluster.
     * 
     */
    public Optional<Output<PSQLClusterConnectionsArgs>> connections() {
        return Optional.ofNullable(this.connections);
    }

    /**
     * [int] The number of CPU cores per replica.
     * 
     */
    @Import(name="cores")
    private @Nullable Output<Integer> cores;

    /**
     * @return [int] The number of CPU cores per replica.
     * 
     */
    public Optional<Output<Integer>> cores() {
        return Optional.ofNullable(this.cores);
    }

    /**
     * [string] Credentials for the database user to be created. This attribute is immutable(disallowed in update requests).
     * 
     */
    @Import(name="credentials")
    private @Nullable Output<PSQLClusterCredentialsArgs> credentials;

    /**
     * @return [string] Credentials for the database user to be created. This attribute is immutable(disallowed in update requests).
     * 
     */
    public Optional<Output<PSQLClusterCredentialsArgs>> credentials() {
        return Optional.ofNullable(this.credentials);
    }

    /**
     * [string] The friendly name of your cluster.
     * 
     */
    @Import(name="displayName")
    private @Nullable Output<String> displayName;

    /**
     * @return [string] The friendly name of your cluster.
     * 
     */
    public Optional<Output<String>> displayName() {
        return Optional.ofNullable(this.displayName);
    }

    /**
     * [string] The DNS name pointing to your cluster.
     * 
     */
    @Import(name="dnsName")
    private @Nullable Output<String> dnsName;

    /**
     * @return [string] The DNS name pointing to your cluster.
     * 
     */
    public Optional<Output<String>> dnsName() {
        return Optional.ofNullable(this.dnsName);
    }

    /**
     * [string] The unique ID of the backup you want to restore. This attribute is immutable(disallowed in update requests).
     * 
     */
    @Import(name="fromBackup")
    private @Nullable Output<PSQLClusterFromBackupArgs> fromBackup;

    /**
     * @return [string] The unique ID of the backup you want to restore. This attribute is immutable(disallowed in update requests).
     * 
     */
    public Optional<Output<PSQLClusterFromBackupArgs>> fromBackup() {
        return Optional.ofNullable(this.fromBackup);
    }

    /**
     * [int] The total number of instances in the cluster (one master and n-1 standbys)
     * 
     */
    @Import(name="instances")
    private @Nullable Output<Integer> instances;

    /**
     * @return [int] The total number of instances in the cluster (one master and n-1 standbys)
     * 
     */
    public Optional<Output<Integer>> instances() {
        return Optional.ofNullable(this.instances);
    }

    /**
     * [string] The physical location where the cluster will be created. This will be where all of your instances live. Property cannot be modified after datacenter creation. Possible values are: `de/fra`, `de/txl`, `gb/lhr`, `es/vit`, `us/ewr`, `us/las`. This attribute is immutable(disallowed in update requests).
     * 
     */
    @Import(name="location")
    private @Nullable Output<String> location;

    /**
     * @return [string] The physical location where the cluster will be created. This will be where all of your instances live. Property cannot be modified after datacenter creation. Possible values are: `de/fra`, `de/txl`, `gb/lhr`, `es/vit`, `us/ewr`, `us/las`. This attribute is immutable(disallowed in update requests).
     * 
     */
    public Optional<Output<String>> location() {
        return Optional.ofNullable(this.location);
    }

    /**
     * (Computed) A weekly 4 hour-long window, during which maintenance might occur
     * 
     */
    @Import(name="maintenanceWindow")
    private @Nullable Output<PSQLClusterMaintenanceWindowArgs> maintenanceWindow;

    /**
     * @return (Computed) A weekly 4 hour-long window, during which maintenance might occur
     * 
     */
    public Optional<Output<PSQLClusterMaintenanceWindowArgs>> maintenanceWindow() {
        return Optional.ofNullable(this.maintenanceWindow);
    }

    /**
     * [string] The PostgreSQL version of your cluster.
     * 
     */
    @Import(name="postgresVersion")
    private @Nullable Output<String> postgresVersion;

    /**
     * @return [string] The PostgreSQL version of your cluster.
     * 
     */
    public Optional<Output<String>> postgresVersion() {
        return Optional.ofNullable(this.postgresVersion);
    }

    /**
     * [int] The amount of memory per instance in megabytes. Has to be a multiple of 1024.
     * 
     */
    @Import(name="ram")
    private @Nullable Output<Integer> ram;

    /**
     * @return [int] The amount of memory per instance in megabytes. Has to be a multiple of 1024.
     * 
     */
    public Optional<Output<Integer>> ram() {
        return Optional.ofNullable(this.ram);
    }

    /**
     * [int] The amount of storage per instance in MB. Has to be a multiple of 2048.
     * 
     */
    @Import(name="storageSize")
    private @Nullable Output<Integer> storageSize;

    /**
     * @return [int] The amount of storage per instance in MB. Has to be a multiple of 2048.
     * 
     */
    public Optional<Output<Integer>> storageSize() {
        return Optional.ofNullable(this.storageSize);
    }

    /**
     * [string] SSD, SSD Standard, SSD Premium, or HDD. Value &#34;SSD&#34; is deprecated, use the equivalent &#34;SSD Premium&#34; instead. This attribute is immutable(disallowed in update requests).
     * 
     */
    @Import(name="storageType")
    private @Nullable Output<String> storageType;

    /**
     * @return [string] SSD, SSD Standard, SSD Premium, or HDD. Value &#34;SSD&#34; is deprecated, use the equivalent &#34;SSD Premium&#34; instead. This attribute is immutable(disallowed in update requests).
     * 
     */
    public Optional<Output<String>> storageType() {
        return Optional.ofNullable(this.storageType);
    }

    /**
     * [string] Represents different modes of replication. Can have one of the following values: ASYNCHRONOUS, SYNCHRONOUS, STRICTLY_SYNCHRONOUS. This attribute is immutable(disallowed in update requests).
     * 
     */
    @Import(name="synchronizationMode")
    private @Nullable Output<String> synchronizationMode;

    /**
     * @return [string] Represents different modes of replication. Can have one of the following values: ASYNCHRONOUS, SYNCHRONOUS, STRICTLY_SYNCHRONOUS. This attribute is immutable(disallowed in update requests).
     * 
     */
    public Optional<Output<String>> synchronizationMode() {
        return Optional.ofNullable(this.synchronizationMode);
    }

    private PSQLClusterState() {}

    private PSQLClusterState(PSQLClusterState $) {
        this.backupLocation = $.backupLocation;
        this.connectionPooler = $.connectionPooler;
        this.connections = $.connections;
        this.cores = $.cores;
        this.credentials = $.credentials;
        this.displayName = $.displayName;
        this.dnsName = $.dnsName;
        this.fromBackup = $.fromBackup;
        this.instances = $.instances;
        this.location = $.location;
        this.maintenanceWindow = $.maintenanceWindow;
        this.postgresVersion = $.postgresVersion;
        this.ram = $.ram;
        this.storageSize = $.storageSize;
        this.storageType = $.storageType;
        this.synchronizationMode = $.synchronizationMode;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(PSQLClusterState defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private PSQLClusterState $;

        public Builder() {
            $ = new PSQLClusterState();
        }

        public Builder(PSQLClusterState defaults) {
            $ = new PSQLClusterState(Objects.requireNonNull(defaults));
        }

        /**
         * @param backupLocation (Computed)[string] The IONOS Object Storage location where the backups will be stored. Possible values are: `de`, `eu-south-2`, `eu-central-2`. This attribute is immutable (disallowed in update requests).
         * 
         * @return builder
         * 
         */
        public Builder backupLocation(@Nullable Output<String> backupLocation) {
            $.backupLocation = backupLocation;
            return this;
        }

        /**
         * @param backupLocation (Computed)[string] The IONOS Object Storage location where the backups will be stored. Possible values are: `de`, `eu-south-2`, `eu-central-2`. This attribute is immutable (disallowed in update requests).
         * 
         * @return builder
         * 
         */
        public Builder backupLocation(String backupLocation) {
            return backupLocation(Output.of(backupLocation));
        }

        /**
         * @param connectionPooler [object]
         * 
         * @return builder
         * 
         */
        public Builder connectionPooler(@Nullable Output<PSQLClusterConnectionPoolerArgs> connectionPooler) {
            $.connectionPooler = connectionPooler;
            return this;
        }

        /**
         * @param connectionPooler [object]
         * 
         * @return builder
         * 
         */
        public Builder connectionPooler(PSQLClusterConnectionPoolerArgs connectionPooler) {
            return connectionPooler(Output.of(connectionPooler));
        }

        /**
         * @param connections [string] Details about the network connection for your cluster.
         * 
         * @return builder
         * 
         */
        public Builder connections(@Nullable Output<PSQLClusterConnectionsArgs> connections) {
            $.connections = connections;
            return this;
        }

        /**
         * @param connections [string] Details about the network connection for your cluster.
         * 
         * @return builder
         * 
         */
        public Builder connections(PSQLClusterConnectionsArgs connections) {
            return connections(Output.of(connections));
        }

        /**
         * @param cores [int] The number of CPU cores per replica.
         * 
         * @return builder
         * 
         */
        public Builder cores(@Nullable Output<Integer> cores) {
            $.cores = cores;
            return this;
        }

        /**
         * @param cores [int] The number of CPU cores per replica.
         * 
         * @return builder
         * 
         */
        public Builder cores(Integer cores) {
            return cores(Output.of(cores));
        }

        /**
         * @param credentials [string] Credentials for the database user to be created. This attribute is immutable(disallowed in update requests).
         * 
         * @return builder
         * 
         */
        public Builder credentials(@Nullable Output<PSQLClusterCredentialsArgs> credentials) {
            $.credentials = credentials;
            return this;
        }

        /**
         * @param credentials [string] Credentials for the database user to be created. This attribute is immutable(disallowed in update requests).
         * 
         * @return builder
         * 
         */
        public Builder credentials(PSQLClusterCredentialsArgs credentials) {
            return credentials(Output.of(credentials));
        }

        /**
         * @param displayName [string] The friendly name of your cluster.
         * 
         * @return builder
         * 
         */
        public Builder displayName(@Nullable Output<String> displayName) {
            $.displayName = displayName;
            return this;
        }

        /**
         * @param displayName [string] The friendly name of your cluster.
         * 
         * @return builder
         * 
         */
        public Builder displayName(String displayName) {
            return displayName(Output.of(displayName));
        }

        /**
         * @param dnsName [string] The DNS name pointing to your cluster.
         * 
         * @return builder
         * 
         */
        public Builder dnsName(@Nullable Output<String> dnsName) {
            $.dnsName = dnsName;
            return this;
        }

        /**
         * @param dnsName [string] The DNS name pointing to your cluster.
         * 
         * @return builder
         * 
         */
        public Builder dnsName(String dnsName) {
            return dnsName(Output.of(dnsName));
        }

        /**
         * @param fromBackup [string] The unique ID of the backup you want to restore. This attribute is immutable(disallowed in update requests).
         * 
         * @return builder
         * 
         */
        public Builder fromBackup(@Nullable Output<PSQLClusterFromBackupArgs> fromBackup) {
            $.fromBackup = fromBackup;
            return this;
        }

        /**
         * @param fromBackup [string] The unique ID of the backup you want to restore. This attribute is immutable(disallowed in update requests).
         * 
         * @return builder
         * 
         */
        public Builder fromBackup(PSQLClusterFromBackupArgs fromBackup) {
            return fromBackup(Output.of(fromBackup));
        }

        /**
         * @param instances [int] The total number of instances in the cluster (one master and n-1 standbys)
         * 
         * @return builder
         * 
         */
        public Builder instances(@Nullable Output<Integer> instances) {
            $.instances = instances;
            return this;
        }

        /**
         * @param instances [int] The total number of instances in the cluster (one master and n-1 standbys)
         * 
         * @return builder
         * 
         */
        public Builder instances(Integer instances) {
            return instances(Output.of(instances));
        }

        /**
         * @param location [string] The physical location where the cluster will be created. This will be where all of your instances live. Property cannot be modified after datacenter creation. Possible values are: `de/fra`, `de/txl`, `gb/lhr`, `es/vit`, `us/ewr`, `us/las`. This attribute is immutable(disallowed in update requests).
         * 
         * @return builder
         * 
         */
        public Builder location(@Nullable Output<String> location) {
            $.location = location;
            return this;
        }

        /**
         * @param location [string] The physical location where the cluster will be created. This will be where all of your instances live. Property cannot be modified after datacenter creation. Possible values are: `de/fra`, `de/txl`, `gb/lhr`, `es/vit`, `us/ewr`, `us/las`. This attribute is immutable(disallowed in update requests).
         * 
         * @return builder
         * 
         */
        public Builder location(String location) {
            return location(Output.of(location));
        }

        /**
         * @param maintenanceWindow (Computed) A weekly 4 hour-long window, during which maintenance might occur
         * 
         * @return builder
         * 
         */
        public Builder maintenanceWindow(@Nullable Output<PSQLClusterMaintenanceWindowArgs> maintenanceWindow) {
            $.maintenanceWindow = maintenanceWindow;
            return this;
        }

        /**
         * @param maintenanceWindow (Computed) A weekly 4 hour-long window, during which maintenance might occur
         * 
         * @return builder
         * 
         */
        public Builder maintenanceWindow(PSQLClusterMaintenanceWindowArgs maintenanceWindow) {
            return maintenanceWindow(Output.of(maintenanceWindow));
        }

        /**
         * @param postgresVersion [string] The PostgreSQL version of your cluster.
         * 
         * @return builder
         * 
         */
        public Builder postgresVersion(@Nullable Output<String> postgresVersion) {
            $.postgresVersion = postgresVersion;
            return this;
        }

        /**
         * @param postgresVersion [string] The PostgreSQL version of your cluster.
         * 
         * @return builder
         * 
         */
        public Builder postgresVersion(String postgresVersion) {
            return postgresVersion(Output.of(postgresVersion));
        }

        /**
         * @param ram [int] The amount of memory per instance in megabytes. Has to be a multiple of 1024.
         * 
         * @return builder
         * 
         */
        public Builder ram(@Nullable Output<Integer> ram) {
            $.ram = ram;
            return this;
        }

        /**
         * @param ram [int] The amount of memory per instance in megabytes. Has to be a multiple of 1024.
         * 
         * @return builder
         * 
         */
        public Builder ram(Integer ram) {
            return ram(Output.of(ram));
        }

        /**
         * @param storageSize [int] The amount of storage per instance in MB. Has to be a multiple of 2048.
         * 
         * @return builder
         * 
         */
        public Builder storageSize(@Nullable Output<Integer> storageSize) {
            $.storageSize = storageSize;
            return this;
        }

        /**
         * @param storageSize [int] The amount of storage per instance in MB. Has to be a multiple of 2048.
         * 
         * @return builder
         * 
         */
        public Builder storageSize(Integer storageSize) {
            return storageSize(Output.of(storageSize));
        }

        /**
         * @param storageType [string] SSD, SSD Standard, SSD Premium, or HDD. Value &#34;SSD&#34; is deprecated, use the equivalent &#34;SSD Premium&#34; instead. This attribute is immutable(disallowed in update requests).
         * 
         * @return builder
         * 
         */
        public Builder storageType(@Nullable Output<String> storageType) {
            $.storageType = storageType;
            return this;
        }

        /**
         * @param storageType [string] SSD, SSD Standard, SSD Premium, or HDD. Value &#34;SSD&#34; is deprecated, use the equivalent &#34;SSD Premium&#34; instead. This attribute is immutable(disallowed in update requests).
         * 
         * @return builder
         * 
         */
        public Builder storageType(String storageType) {
            return storageType(Output.of(storageType));
        }

        /**
         * @param synchronizationMode [string] Represents different modes of replication. Can have one of the following values: ASYNCHRONOUS, SYNCHRONOUS, STRICTLY_SYNCHRONOUS. This attribute is immutable(disallowed in update requests).
         * 
         * @return builder
         * 
         */
        public Builder synchronizationMode(@Nullable Output<String> synchronizationMode) {
            $.synchronizationMode = synchronizationMode;
            return this;
        }

        /**
         * @param synchronizationMode [string] Represents different modes of replication. Can have one of the following values: ASYNCHRONOUS, SYNCHRONOUS, STRICTLY_SYNCHRONOUS. This attribute is immutable(disallowed in update requests).
         * 
         * @return builder
         * 
         */
        public Builder synchronizationMode(String synchronizationMode) {
            return synchronizationMode(Output.of(synchronizationMode));
        }

        public PSQLClusterState build() {
            return $;
        }
    }

}
