// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Ionoscloud.Dbaas.Inputs
{

    public sealed class MongoClusterBiConnectorGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Enable or disable the BiConnector.
        /// </summary>
        [Input("enabled")]
        public Input<bool>? Enabled { get; set; }

        /// <summary>
        /// The host where this new BI Connector is installed.
        /// </summary>
        [Input("host")]
        public Input<string>? Host { get; set; }

        /// <summary>
        /// Port number used when connecting to this new BI Connector.
        /// </summary>
        [Input("port")]
        public Input<string>? Port { get; set; }

        public MongoClusterBiConnectorGetArgs()
        {
        }
        public static new MongoClusterBiConnectorGetArgs Empty => new MongoClusterBiConnectorGetArgs();
    }
}
