name: Setup tools
description: Installs Go, Pulumi, pulumictl, schema-tools, Node.JS, Python, dotnet and Java.

inputs:
  tools:
    description: |
      Comma separated list of tools to install. The default of "all" installs all tools. Available tools are:
        go
        pulumicli
        pulumictl
        schema-tools
        nodejs
        python
        dotnet
        java
    default: all
  cache-go:
    description: |
      Whether to enable the GitHub cache for Go. Appropriate for disabling in
      smaller jobs that typically completely before the "real" job has an
      opportunity to populate the cache.
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Install Go
      if: inputs.tools == 'all' || contains(inputs.tools, 'go')
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # ratchet:actions/setup-go@v6.4.0
      with:
        go-version: "1.26.x"
        cache-dependency-path: |
          provider/*.sum
          upstream/*.sum
          sdk/go/*.sum
          sdk/*.sum
          *.sum
        # TODO(https://github.com/actions/setup-go/issues/316): Restore but don't save the cache.
        cache: ${{ inputs.cache-go }}

    - name: Install pulumictl
      if: inputs.tools == 'all' || contains(inputs.tools, 'pulumictl')
      uses: jaxxstorm/action-install-gh-release@25e24d2d23ae098373794ef1d6faecb48ee52da8 # ratchet:jaxxstorm/action-install-gh-release@v3.0.0
      with:
        tag: v0.0.48
        repo: pulumi/pulumictl

    - name: Install Pulumi CLI
      if: inputs.tools == 'all' || contains(inputs.tools, 'pulumicli')
      uses: pulumi/actions@8582a9e8cc630786854029b4e09281acd6794b58 # ratchet:pulumi/actions@v6.6.1
      with:
        pulumi-version: "dev"

    - name: Install Schema Tools
      if: inputs.tools == 'all' || contains(inputs.tools, 'schema-tools')
      uses: jaxxstorm/action-install-gh-release@25e24d2d23ae098373794ef1d6faecb48ee52da8 # ratchet:jaxxstorm/action-install-gh-release@v3.0.0
      with:
        repo: pulumi/schema-tools

    - name: Setup Node
      if: inputs.tools == 'all' || contains(inputs.tools, 'nodejs')
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # ratchet:actions/setup-node@v6.3.0
      with:
        node-version: 20.x
        registry-url: https://registry.npmjs.org

    - name: Setup DotNet
      if: inputs.tools == 'all' || contains(inputs.tools, 'dotnet')
      uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # ratchet:actions/setup-dotnet@v5.2.0
      with:
        dotnet-version: 8.0.x

    - name: Setup Python
      if: inputs.tools == 'all' || contains(inputs.tools, 'python')
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # ratchet:actions/setup-python@v6.2.0
      with:
        python-version: 3.11.8

    - name: Setup Java
      if: inputs.tools == 'all' || contains(inputs.tools, 'java')
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # ratchet:actions/setup-java@v5.2.0
      with:
        cache: gradle
        distribution: temurin
        java-version: 11

    - name: Setup Gradle
      if: inputs.tools == 'all' || contains(inputs.tools, 'java')
      uses: gradle/gradle-build-action@ac2d340dc04d9e1113182899e983b5400c17cda1 # ratchet:gradle/gradle-build-action@v3.5.0
      with:
        gradle-version: 7.6
