// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Ionoscloud.Pulumi.Ionoscloud.Objectstorage
{
    /// <summary>
    /// Manages Website Configuration for Buckets on IonosCloud.
    /// 
    /// ⚠️ **Note:** The Terraform provider **only supports contract-owned buckets. User-owned buckets are not supported,** and there are no plans to introduce support for them. As a result, **user-owned buckets cannot be created, updated, deleted, read, or imported** using this provider.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using System.Collections.Generic;
    /// using System.Linq;
    /// using Pulumi;
    /// using Ionoscloud = Ionoscloud.Pulumi.Ionoscloud;
    /// 
    /// return await Deployment.RunAsync(() =&gt; 
    /// {
    ///     var example = new Ionoscloud.Objectstorage.Bucket("example", new()
    ///     {
    ///         Name = "example",
    ///     });
    /// 
    ///     var exampleWebsiteConfiguration = new Ionoscloud.Objectstorage.WebsiteConfiguration("example", new()
    ///     {
    ///         Bucket = example.Name,
    ///         IndexDocument = new[]
    ///         {
    ///             
    ///             {
    ///                 { "suffix", "index.html" },
    ///             },
    ///         },
    ///         ErrorDocument = new[]
    ///         {
    ///             
    ///             {
    ///                 { "key", "error.html" },
    ///             },
    ///         },
    ///         RoutingRules = new[]
    ///         {
    ///             new Ionoscloud.Objectstorage.Inputs.WebsiteConfigurationRoutingRuleArgs
    ///             {
    ///                 Condition = new[]
    ///                 {
    ///                     
    ///                     {
    ///                         { "keyPrefixEquals", "docs/" },
    ///                     },
    ///                 },
    ///                 Redirect = new[]
    ///                 {
    ///                     
    ///                     {
    ///                         { "replaceKeyPrefixWith", "documents/" },
    ///                     },
    ///                 },
    ///             },
    ///         },
    ///     });
    /// 
    /// });
    /// ```
    /// 
    /// ## Import
    /// 
    /// IONOS Object Storage Bucket website configuration can be imported using the `Bucket` name.
    /// 
    /// ```sh
    /// $ pulumi import ionoscloud:objectstorage/websiteConfiguration:WebsiteConfiguration example example
    /// ```
    /// </summary>
    [IonoscloudResourceType("ionoscloud:objectstorage/websiteConfiguration:WebsiteConfiguration")]
    public partial class WebsiteConfiguration : global::Pulumi.CustomResource
    {
        /// <summary>
        /// [string] The name of the bucket where the object will be stored.
        /// </summary>
        [Output("bucket")]
        public Output<string> Bucket { get; private set; } = null!;

        /// <summary>
        /// The object key name to use when a 4XX class error occurs. Replacement must be made for object keys containing special characters (such as carriage returns) when using XML requests
        /// </summary>
        [Output("errorDocument")]
        public Output<Outputs.WebsiteConfigurationErrorDocument?> ErrorDocument { get; private set; } = null!;

        /// <summary>
        /// Container for the Suffix element.
        /// </summary>
        [Output("indexDocument")]
        public Output<Outputs.WebsiteConfigurationIndexDocument?> IndexDocument { get; private set; } = null!;

        /// <summary>
        /// Container for redirect information. You can redirect requests to another host, to another page, or with another protocol. In the event of an error, you can can specify a different error code to return.
        /// </summary>
        [Output("redirectAllRequestsTo")]
        public Output<Outputs.WebsiteConfigurationRedirectAllRequestsTo?> RedirectAllRequestsTo { get; private set; } = null!;

        /// <summary>
        /// A container for describing a condition that must be met for the specified redirect to apply.
        /// </summary>
        [Output("routingRules")]
        public Output<ImmutableArray<Outputs.WebsiteConfigurationRoutingRule>> RoutingRules { get; private set; } = null!;


        /// <summary>
        /// Create a WebsiteConfiguration resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public WebsiteConfiguration(string name, WebsiteConfigurationArgs args, CustomResourceOptions? options = null)
            : base("ionoscloud:objectstorage/websiteConfiguration:WebsiteConfiguration", name, args ?? new WebsiteConfigurationArgs(), MakeResourceOptions(options, ""))
        {
        }

        private WebsiteConfiguration(string name, Input<string> id, WebsiteConfigurationState? state = null, CustomResourceOptions? options = null)
            : base("ionoscloud:objectstorage/websiteConfiguration:WebsiteConfiguration", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/ionos-cloud",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing WebsiteConfiguration resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static WebsiteConfiguration Get(string name, Input<string> id, WebsiteConfigurationState? state = null, CustomResourceOptions? options = null)
        {
            return new WebsiteConfiguration(name, id, state, options);
        }
    }

    public sealed class WebsiteConfigurationArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// [string] The name of the bucket where the object will be stored.
        /// </summary>
        [Input("bucket", required: true)]
        public Input<string> Bucket { get; set; } = null!;

        /// <summary>
        /// The object key name to use when a 4XX class error occurs. Replacement must be made for object keys containing special characters (such as carriage returns) when using XML requests
        /// </summary>
        [Input("errorDocument")]
        public Input<Inputs.WebsiteConfigurationErrorDocumentArgs>? ErrorDocument { get; set; }

        /// <summary>
        /// Container for the Suffix element.
        /// </summary>
        [Input("indexDocument")]
        public Input<Inputs.WebsiteConfigurationIndexDocumentArgs>? IndexDocument { get; set; }

        /// <summary>
        /// Container for redirect information. You can redirect requests to another host, to another page, or with another protocol. In the event of an error, you can can specify a different error code to return.
        /// </summary>
        [Input("redirectAllRequestsTo")]
        public Input<Inputs.WebsiteConfigurationRedirectAllRequestsToArgs>? RedirectAllRequestsTo { get; set; }

        [Input("routingRules")]
        private InputList<Inputs.WebsiteConfigurationRoutingRuleArgs>? _routingRules;

        /// <summary>
        /// A container for describing a condition that must be met for the specified redirect to apply.
        /// </summary>
        public InputList<Inputs.WebsiteConfigurationRoutingRuleArgs> RoutingRules
        {
            get => _routingRules ?? (_routingRules = new InputList<Inputs.WebsiteConfigurationRoutingRuleArgs>());
            set => _routingRules = value;
        }

        public WebsiteConfigurationArgs()
        {
        }
        public static new WebsiteConfigurationArgs Empty => new WebsiteConfigurationArgs();
    }

    public sealed class WebsiteConfigurationState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// [string] The name of the bucket where the object will be stored.
        /// </summary>
        [Input("bucket")]
        public Input<string>? Bucket { get; set; }

        /// <summary>
        /// The object key name to use when a 4XX class error occurs. Replacement must be made for object keys containing special characters (such as carriage returns) when using XML requests
        /// </summary>
        [Input("errorDocument")]
        public Input<Inputs.WebsiteConfigurationErrorDocumentGetArgs>? ErrorDocument { get; set; }

        /// <summary>
        /// Container for the Suffix element.
        /// </summary>
        [Input("indexDocument")]
        public Input<Inputs.WebsiteConfigurationIndexDocumentGetArgs>? IndexDocument { get; set; }

        /// <summary>
        /// Container for redirect information. You can redirect requests to another host, to another page, or with another protocol. In the event of an error, you can can specify a different error code to return.
        /// </summary>
        [Input("redirectAllRequestsTo")]
        public Input<Inputs.WebsiteConfigurationRedirectAllRequestsToGetArgs>? RedirectAllRequestsTo { get; set; }

        [Input("routingRules")]
        private InputList<Inputs.WebsiteConfigurationRoutingRuleGetArgs>? _routingRules;

        /// <summary>
        /// A container for describing a condition that must be met for the specified redirect to apply.
        /// </summary>
        public InputList<Inputs.WebsiteConfigurationRoutingRuleGetArgs> RoutingRules
        {
            get => _routingRules ?? (_routingRules = new InputList<Inputs.WebsiteConfigurationRoutingRuleGetArgs>());
            set => _routingRules = value;
        }

        public WebsiteConfigurationState()
        {
        }
        public static new WebsiteConfigurationState Empty => new WebsiteConfigurationState();
    }
}
