// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package compute

import (
	"context"
	"reflect"

	"github.com/ionos-cloud/pulumi-ionoscloud/sdk/go/ionoscloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The [GPU Server data source](https://docs.ionos.com/cloud/compute-services/compute-engine/cloud-gpu-vm) can be used to search for and return existing GPU servers.
// If a single match is found, it will be returned. If your search results in multiple matches, an error will be returned.
// When this happens, please refine your search string so that it is specific enough to return only one result.
//
// ## Example Usage
//
// ### By ID
// ```go
// package main
//
// import (
//
//	"github.com/ionos-cloud/pulumi-ionoscloud/sdk/go/ionoscloud/compute"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := compute.LookupGPUServer(ctx, &compute.LookupGPUServerArgs{
//				DatacenterId: "datacenter_id",
//				Id:           pulumi.StringRef("server_id"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ### By Name
// ```go
// package main
//
// import (
//
//	"github.com/ionos-cloud/pulumi-ionoscloud/sdk/go/ionoscloud/compute"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := compute.LookupGPUServer(ctx, &compute.LookupGPUServerArgs{
//				DatacenterId: "datacenter_id",
//				Name:         pulumi.StringRef("GPU Server Example"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func LookupGPUServer(ctx *pulumi.Context, args *LookupGPUServerArgs, opts ...pulumi.InvokeOption) (*LookupGPUServerResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupGPUServerResult
	err := ctx.Invoke("ionoscloud:compute/getGPUServer:getGPUServer", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getGPUServer.
type LookupGPUServerArgs struct {
	// Datacenter's UUID.
	DatacenterId string `pulumi:"datacenterId"`
	// ID of the server you want to search for.
	//
	// `datacenterId` and either `name` or `id` must be provided. If none, or both of `name` and `id` are provided, the datasource will return an error.
	Id *string `pulumi:"id"`
	// Location of that image/snapshot
	Location *string `pulumi:"location"`
	// Name of an existing server that you want to search for.
	Name *string `pulumi:"name"`
	// The UUID of the template for creating a GPU server; the available templates for GPU servers can be found on the templates resource
	TemplateUuid *string `pulumi:"templateUuid"`
}

// A collection of values returned by getGPUServer.
type LookupGPUServerResult struct {
	// The availability zone in which the volume should exist
	AvailabilityZone string `pulumi:"availabilityZone"`
	BootCdrom        string `pulumi:"bootCdrom"`
	BootImage        string `pulumi:"bootImage"`
	BootVolume       string `pulumi:"bootVolume"`
	// list of
	Cdroms    []GetGPUServerCdrom `pulumi:"cdroms"`
	Cores     int                 `pulumi:"cores"`
	CpuFamily string              `pulumi:"cpuFamily"`
	// The id of the datacenter
	DatacenterId string `pulumi:"datacenterId"`
	// The hostname of the server
	Hostname string `pulumi:"hostname"`
	// Id of the attached volume
	Id string `pulumi:"id"`
	// Location of that image/snapshot
	Location *string `pulumi:"location"`
	// Name of the attached volume
	Name              string            `pulumi:"name"`
	Nics              []GetGPUServerNic `pulumi:"nics"`
	Ram               int               `pulumi:"ram"`
	SecurityGroupsIds []string          `pulumi:"securityGroupsIds"`
	// The UUID of the template for creating a GPU server; the available templates for GPU servers can be found on the templates resource
	TemplateUuid *string `pulumi:"templateUuid"`
	Token        string  `pulumi:"token"`
	// Status of the virtual Machine
	VmState string `pulumi:"vmState"`
	// list of
	Volumes []GetGPUServerVolume `pulumi:"volumes"`
}

func LookupGPUServerOutput(ctx *pulumi.Context, args LookupGPUServerOutputArgs, opts ...pulumi.InvokeOption) LookupGPUServerResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupGPUServerResultOutput, error) {
			args := v.(LookupGPUServerArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("ionoscloud:compute/getGPUServer:getGPUServer", args, LookupGPUServerResultOutput{}, options).(LookupGPUServerResultOutput), nil
		}).(LookupGPUServerResultOutput)
}

// A collection of arguments for invoking getGPUServer.
type LookupGPUServerOutputArgs struct {
	// Datacenter's UUID.
	DatacenterId pulumi.StringInput `pulumi:"datacenterId"`
	// ID of the server you want to search for.
	//
	// `datacenterId` and either `name` or `id` must be provided. If none, or both of `name` and `id` are provided, the datasource will return an error.
	Id pulumi.StringPtrInput `pulumi:"id"`
	// Location of that image/snapshot
	Location pulumi.StringPtrInput `pulumi:"location"`
	// Name of an existing server that you want to search for.
	Name pulumi.StringPtrInput `pulumi:"name"`
	// The UUID of the template for creating a GPU server; the available templates for GPU servers can be found on the templates resource
	TemplateUuid pulumi.StringPtrInput `pulumi:"templateUuid"`
}

func (LookupGPUServerOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupGPUServerArgs)(nil)).Elem()
}

// A collection of values returned by getGPUServer.
type LookupGPUServerResultOutput struct{ *pulumi.OutputState }

func (LookupGPUServerResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupGPUServerResult)(nil)).Elem()
}

func (o LookupGPUServerResultOutput) ToLookupGPUServerResultOutput() LookupGPUServerResultOutput {
	return o
}

func (o LookupGPUServerResultOutput) ToLookupGPUServerResultOutputWithContext(ctx context.Context) LookupGPUServerResultOutput {
	return o
}

// The availability zone in which the volume should exist
func (o LookupGPUServerResultOutput) AvailabilityZone() pulumi.StringOutput {
	return o.ApplyT(func(v LookupGPUServerResult) string { return v.AvailabilityZone }).(pulumi.StringOutput)
}

func (o LookupGPUServerResultOutput) BootCdrom() pulumi.StringOutput {
	return o.ApplyT(func(v LookupGPUServerResult) string { return v.BootCdrom }).(pulumi.StringOutput)
}

func (o LookupGPUServerResultOutput) BootImage() pulumi.StringOutput {
	return o.ApplyT(func(v LookupGPUServerResult) string { return v.BootImage }).(pulumi.StringOutput)
}

func (o LookupGPUServerResultOutput) BootVolume() pulumi.StringOutput {
	return o.ApplyT(func(v LookupGPUServerResult) string { return v.BootVolume }).(pulumi.StringOutput)
}

// list of
func (o LookupGPUServerResultOutput) Cdroms() GetGPUServerCdromArrayOutput {
	return o.ApplyT(func(v LookupGPUServerResult) []GetGPUServerCdrom { return v.Cdroms }).(GetGPUServerCdromArrayOutput)
}

func (o LookupGPUServerResultOutput) Cores() pulumi.IntOutput {
	return o.ApplyT(func(v LookupGPUServerResult) int { return v.Cores }).(pulumi.IntOutput)
}

func (o LookupGPUServerResultOutput) CpuFamily() pulumi.StringOutput {
	return o.ApplyT(func(v LookupGPUServerResult) string { return v.CpuFamily }).(pulumi.StringOutput)
}

// The id of the datacenter
func (o LookupGPUServerResultOutput) DatacenterId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupGPUServerResult) string { return v.DatacenterId }).(pulumi.StringOutput)
}

// The hostname of the server
func (o LookupGPUServerResultOutput) Hostname() pulumi.StringOutput {
	return o.ApplyT(func(v LookupGPUServerResult) string { return v.Hostname }).(pulumi.StringOutput)
}

// Id of the attached volume
func (o LookupGPUServerResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupGPUServerResult) string { return v.Id }).(pulumi.StringOutput)
}

// Location of that image/snapshot
func (o LookupGPUServerResultOutput) Location() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupGPUServerResult) *string { return v.Location }).(pulumi.StringPtrOutput)
}

// Name of the attached volume
func (o LookupGPUServerResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupGPUServerResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupGPUServerResultOutput) Nics() GetGPUServerNicArrayOutput {
	return o.ApplyT(func(v LookupGPUServerResult) []GetGPUServerNic { return v.Nics }).(GetGPUServerNicArrayOutput)
}

func (o LookupGPUServerResultOutput) Ram() pulumi.IntOutput {
	return o.ApplyT(func(v LookupGPUServerResult) int { return v.Ram }).(pulumi.IntOutput)
}

func (o LookupGPUServerResultOutput) SecurityGroupsIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupGPUServerResult) []string { return v.SecurityGroupsIds }).(pulumi.StringArrayOutput)
}

// The UUID of the template for creating a GPU server; the available templates for GPU servers can be found on the templates resource
func (o LookupGPUServerResultOutput) TemplateUuid() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupGPUServerResult) *string { return v.TemplateUuid }).(pulumi.StringPtrOutput)
}

func (o LookupGPUServerResultOutput) Token() pulumi.StringOutput {
	return o.ApplyT(func(v LookupGPUServerResult) string { return v.Token }).(pulumi.StringOutput)
}

// Status of the virtual Machine
func (o LookupGPUServerResultOutput) VmState() pulumi.StringOutput {
	return o.ApplyT(func(v LookupGPUServerResult) string { return v.VmState }).(pulumi.StringOutput)
}

// list of
func (o LookupGPUServerResultOutput) Volumes() GetGPUServerVolumeArrayOutput {
	return o.ApplyT(func(v LookupGPUServerResult) []GetGPUServerVolume { return v.Volumes }).(GetGPUServerVolumeArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupGPUServerResultOutput{})
}
