// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.ionoscloud.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetLoggingPipelineLogDestination {
    /**
     * @return [int] Defines the number of days a log record should be kept in loki. Works with loki destination type only.
     * 
     */
    private Integer retentionInDays;
    /**
     * @return [string] The internal output stream to send logs to.
     * 
     */
    private String type;

    private GetLoggingPipelineLogDestination() {}
    /**
     * @return [int] Defines the number of days a log record should be kept in loki. Works with loki destination type only.
     * 
     */
    public Integer retentionInDays() {
        return this.retentionInDays;
    }
    /**
     * @return [string] The internal output stream to send logs to.
     * 
     */
    public String type() {
        return this.type;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetLoggingPipelineLogDestination defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private Integer retentionInDays;
        private String type;
        public Builder() {}
        public Builder(GetLoggingPipelineLogDestination defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.retentionInDays = defaults.retentionInDays;
    	      this.type = defaults.type;
        }

        @CustomType.Setter
        public Builder retentionInDays(Integer retentionInDays) {
            if (retentionInDays == null) {
              throw new MissingRequiredPropertyException("GetLoggingPipelineLogDestination", "retentionInDays");
            }
            this.retentionInDays = retentionInDays;
            return this;
        }
        @CustomType.Setter
        public Builder type(String type) {
            if (type == null) {
              throw new MissingRequiredPropertyException("GetLoggingPipelineLogDestination", "type");
            }
            this.type = type;
            return this;
        }
        public GetLoggingPipelineLogDestination build() {
            final var _resultValue = new GetLoggingPipelineLogDestination();
            _resultValue.retentionInDays = retentionInDays;
            _resultValue.type = type;
            return _resultValue;
        }
    }
}
