// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Ionoscloud.Pulumi.Ionoscloud.Dbaas
{
    public static class GetInMemoryDBClusterV2
    {
        /// <summary>
        /// The `ionoscloud.dbaas.InMemoryDBClusterV2` data source can be used to retrieve information about an existing InMemoryDB V2 cluster.
        /// 
        /// ## Example Usage
        /// 
        /// ### By id
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Ionoscloud = Ionoscloud.Pulumi.Ionoscloud;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var byId = Ionoscloud.Dbaas.GetInMemoryDBClusterV2.Invoke(new()
        ///     {
        ///         Id = "example-id",
        ///         Location = "de/txl",
        ///     });
        /// 
        /// });
        /// ```
        /// 
        /// ### By name
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Ionoscloud = Ionoscloud.Pulumi.Ionoscloud;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var byName = Ionoscloud.Dbaas.GetInMemoryDBClusterV2.Invoke(new()
        ///     {
        ///         Name = "my-inmemorydb-cluster",
        ///         Location = "de/txl",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetInMemoryDBClusterV2Result> InvokeAsync(GetInMemoryDBClusterV2Args args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetInMemoryDBClusterV2Result>("ionoscloud:dbaas/getInMemoryDBClusterV2:getInMemoryDBClusterV2", args ?? new GetInMemoryDBClusterV2Args(), options.WithDefaults());

        /// <summary>
        /// The `ionoscloud.dbaas.InMemoryDBClusterV2` data source can be used to retrieve information about an existing InMemoryDB V2 cluster.
        /// 
        /// ## Example Usage
        /// 
        /// ### By id
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Ionoscloud = Ionoscloud.Pulumi.Ionoscloud;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var byId = Ionoscloud.Dbaas.GetInMemoryDBClusterV2.Invoke(new()
        ///     {
        ///         Id = "example-id",
        ///         Location = "de/txl",
        ///     });
        /// 
        /// });
        /// ```
        /// 
        /// ### By name
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Ionoscloud = Ionoscloud.Pulumi.Ionoscloud;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var byName = Ionoscloud.Dbaas.GetInMemoryDBClusterV2.Invoke(new()
        ///     {
        ///         Name = "my-inmemorydb-cluster",
        ///         Location = "de/txl",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetInMemoryDBClusterV2Result> Invoke(GetInMemoryDBClusterV2InvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetInMemoryDBClusterV2Result>("ionoscloud:dbaas/getInMemoryDBClusterV2:getInMemoryDBClusterV2", args ?? new GetInMemoryDBClusterV2InvokeArgs(), options.WithDefaults());

        /// <summary>
        /// The `ionoscloud.dbaas.InMemoryDBClusterV2` data source can be used to retrieve information about an existing InMemoryDB V2 cluster.
        /// 
        /// ## Example Usage
        /// 
        /// ### By id
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Ionoscloud = Ionoscloud.Pulumi.Ionoscloud;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var byId = Ionoscloud.Dbaas.GetInMemoryDBClusterV2.Invoke(new()
        ///     {
        ///         Id = "example-id",
        ///         Location = "de/txl",
        ///     });
        /// 
        /// });
        /// ```
        /// 
        /// ### By name
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Ionoscloud = Ionoscloud.Pulumi.Ionoscloud;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var byName = Ionoscloud.Dbaas.GetInMemoryDBClusterV2.Invoke(new()
        ///     {
        ///         Name = "my-inmemorydb-cluster",
        ///         Location = "de/txl",
        ///     });
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetInMemoryDBClusterV2Result> Invoke(GetInMemoryDBClusterV2InvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetInMemoryDBClusterV2Result>("ionoscloud:dbaas/getInMemoryDBClusterV2:getInMemoryDBClusterV2", args ?? new GetInMemoryDBClusterV2InvokeArgs(), options.WithDefaults());
    }


    public sealed class GetInMemoryDBClusterV2Args : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The UUID of the cluster.
        /// </summary>
        [Input("id")]
        public string? Id { get; set; }

        /// <summary>
        /// [string] The location of the cluster.
        /// 
        /// &gt; **Note:** Either `Id` or `Name` must be provided. If none, or both are provided, the datasource will return an error.
        /// </summary>
        [Input("location", required: true)]
        public string Location { get; set; } = null!;

        /// <summary>
        /// The cluster name (exact match).
        /// </summary>
        [Input("name")]
        public string? Name { get; set; }

        public GetInMemoryDBClusterV2Args()
        {
        }
        public static new GetInMemoryDBClusterV2Args Empty => new GetInMemoryDBClusterV2Args();
    }

    public sealed class GetInMemoryDBClusterV2InvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The UUID of the cluster.
        /// </summary>
        [Input("id")]
        public Input<string>? Id { get; set; }

        /// <summary>
        /// [string] The location of the cluster.
        /// 
        /// &gt; **Note:** Either `Id` or `Name` must be provided. If none, or both are provided, the datasource will return an error.
        /// </summary>
        [Input("location", required: true)]
        public Input<string> Location { get; set; } = null!;

        /// <summary>
        /// The cluster name (exact match).
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        public GetInMemoryDBClusterV2InvokeArgs()
        {
        }
        public static new GetInMemoryDBClusterV2InvokeArgs Empty => new GetInMemoryDBClusterV2InvokeArgs();
    }


    [OutputType]
    public sealed class GetInMemoryDBClusterV2Result
    {
        /// <summary>
        /// Network connection configuration:
        /// </summary>
        public readonly Outputs.GetInMemoryDBClusterV2ConnectionsResult Connections;
        /// <summary>
        /// Credentials block:
        /// </summary>
        public readonly Outputs.GetInMemoryDBClusterV2CredentialsResult Credentials;
        /// <summary>
        /// Human-readable description for the cluster.
        /// </summary>
        public readonly string Description;
        /// <summary>
        /// The DNS name for connecting to the cluster's primary instance.
        /// </summary>
        public readonly string DnsName;
        /// <summary>
        /// The key eviction strategy.
        /// </summary>
        public readonly string EvictionPolicy;
        /// <summary>
        /// The UUID of the cluster.
        /// </summary>
        public readonly string Id;
        /// <summary>
        /// Instance sizing configuration:
        /// </summary>
        public readonly Outputs.GetInMemoryDBClusterV2InstancesResult Instances;
        /// <summary>
        /// Object Storage location for snapshots.
        /// </summary>
        public readonly string Location;
        /// <summary>
        /// Whether log collection is enabled.
        /// </summary>
        public readonly bool LogsEnabled;
        /// <summary>
        /// Maintenance window configuration:
        /// </summary>
        public readonly Outputs.GetInMemoryDBClusterV2MaintenanceWindowResult MaintenanceWindow;
        /// <summary>
        /// Whether metrics collection is enabled.
        /// </summary>
        public readonly bool MetricsEnabled;
        /// <summary>
        /// The name of the cluster.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The data persistence mode.
        /// </summary>
        public readonly string PersistenceMode;
        /// <summary>
        /// Snapshot configuration:
        /// </summary>
        public readonly Outputs.GetInMemoryDBClusterV2SnapshotResult Snapshot;
        /// <summary>
        /// The InMemoryDB version.
        /// </summary>
        public readonly string Version;

        [OutputConstructor]
        private GetInMemoryDBClusterV2Result(
            Outputs.GetInMemoryDBClusterV2ConnectionsResult connections,

            Outputs.GetInMemoryDBClusterV2CredentialsResult credentials,

            string description,

            string dnsName,

            string evictionPolicy,

            string id,

            Outputs.GetInMemoryDBClusterV2InstancesResult instances,

            string location,

            bool logsEnabled,

            Outputs.GetInMemoryDBClusterV2MaintenanceWindowResult maintenanceWindow,

            bool metricsEnabled,

            string name,

            string persistenceMode,

            Outputs.GetInMemoryDBClusterV2SnapshotResult snapshot,

            string version)
        {
            Connections = connections;
            Credentials = credentials;
            Description = description;
            DnsName = dnsName;
            EvictionPolicy = evictionPolicy;
            Id = id;
            Instances = instances;
            Location = location;
            LogsEnabled = logsEnabled;
            MaintenanceWindow = maintenanceWindow;
            MetricsEnabled = metricsEnabled;
            Name = name;
            PersistenceMode = persistenceMode;
            Snapshot = snapshot;
            Version = version;
        }
    }
}
