// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getMongoTemplate(args?: GetMongoTemplateArgs, opts?: pulumi.InvokeOptions): Promise<GetMongoTemplateResult> {
    args = args || {};

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("ionoscloud:index/getMongoTemplate:getMongoTemplate", {
        "id": args.id,
        "name": args.name,
        "partialMatch": args.partialMatch,
    }, opts);
}

/**
 * A collection of arguments for invoking getMongoTemplate.
 */
export interface GetMongoTemplateArgs {
    id?: string;
    name?: string;
    partialMatch?: boolean;
}

/**
 * A collection of values returned by getMongoTemplate.
 */
export interface GetMongoTemplateResult {
    readonly cores: number;
    readonly edition: string;
    readonly id: string;
    readonly name: string;
    readonly partialMatch?: boolean;
    readonly ram: number;
    readonly storageSize: number;
}
export function getMongoTemplateOutput(args?: GetMongoTemplateOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetMongoTemplateResult> {
    return pulumi.output(args).apply((a: any) => getMongoTemplate(a, opts))
}

/**
 * A collection of arguments for invoking getMongoTemplate.
 */
export interface GetMongoTemplateOutputArgs {
    id?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    partialMatch?: pulumi.Input<boolean>;
}
