// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package ionoscloud

import (
	"context"
	"reflect"

	"github.com/ionos-cloud/pulumi-ionoscloud/sdk/go/ionoscloud/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The **Object storage region data source** can be used to search for and return an existing S3 Regions.
//
// ## Example Usage
//
// ### By ID
// ```go
// package main
//
// import (
//
//	"github.com/ionos-cloud/pulumi-ionoscloud/sdk/go/ionoscloud"
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := ionoscloud.GetObjectStorageRegion(ctx, &ionoscloud.GetObjectStorageRegionArgs{
//				Id: "region_id",
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
func GetObjectStorageRegion(ctx *pulumi.Context, args *GetObjectStorageRegionArgs, opts ...pulumi.InvokeOption) (*GetObjectStorageRegionResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetObjectStorageRegionResult
	err := ctx.Invoke("ionoscloud:index/getObjectStorageRegion:getObjectStorageRegion", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getObjectStorageRegion.
type GetObjectStorageRegionArgs struct {
	// Id of an existing object storage Region that you want to search for.
	Id string `pulumi:"id"`
}

// A collection of values returned by getObjectStorageRegion.
type GetObjectStorageRegionResult struct {
	// The capabilities of the region
	Capability GetObjectStorageRegionCapability `pulumi:"capability"`
	// The endpoint URL for the region
	Endpoint string `pulumi:"endpoint"`
	// The id of the region
	Id string `pulumi:"id"`
	// The data center location of the region as per [Get Location](https://www.terraform.io/docs/cloud/v6/#tag/Locations/operation/locationsGet). *Can't be used as `LocationConstraint` on bucket creation.*
	Location string `pulumi:"location"`
	// The available classes in the region
	StorageClasses []string `pulumi:"storageClasses"`
	// The version of the region properties
	Version float64 `pulumi:"version"`
	// The website URL for the region
	Website string `pulumi:"website"`
}

func GetObjectStorageRegionOutput(ctx *pulumi.Context, args GetObjectStorageRegionOutputArgs, opts ...pulumi.InvokeOption) GetObjectStorageRegionResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetObjectStorageRegionResultOutput, error) {
			args := v.(GetObjectStorageRegionArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("ionoscloud:index/getObjectStorageRegion:getObjectStorageRegion", args, GetObjectStorageRegionResultOutput{}, options).(GetObjectStorageRegionResultOutput), nil
		}).(GetObjectStorageRegionResultOutput)
}

// A collection of arguments for invoking getObjectStorageRegion.
type GetObjectStorageRegionOutputArgs struct {
	// Id of an existing object storage Region that you want to search for.
	Id pulumi.StringInput `pulumi:"id"`
}

func (GetObjectStorageRegionOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetObjectStorageRegionArgs)(nil)).Elem()
}

// A collection of values returned by getObjectStorageRegion.
type GetObjectStorageRegionResultOutput struct{ *pulumi.OutputState }

func (GetObjectStorageRegionResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetObjectStorageRegionResult)(nil)).Elem()
}

func (o GetObjectStorageRegionResultOutput) ToGetObjectStorageRegionResultOutput() GetObjectStorageRegionResultOutput {
	return o
}

func (o GetObjectStorageRegionResultOutput) ToGetObjectStorageRegionResultOutputWithContext(ctx context.Context) GetObjectStorageRegionResultOutput {
	return o
}

// The capabilities of the region
func (o GetObjectStorageRegionResultOutput) Capability() GetObjectStorageRegionCapabilityOutput {
	return o.ApplyT(func(v GetObjectStorageRegionResult) GetObjectStorageRegionCapability { return v.Capability }).(GetObjectStorageRegionCapabilityOutput)
}

// The endpoint URL for the region
func (o GetObjectStorageRegionResultOutput) Endpoint() pulumi.StringOutput {
	return o.ApplyT(func(v GetObjectStorageRegionResult) string { return v.Endpoint }).(pulumi.StringOutput)
}

// The id of the region
func (o GetObjectStorageRegionResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetObjectStorageRegionResult) string { return v.Id }).(pulumi.StringOutput)
}

// The data center location of the region as per [Get Location](https://www.terraform.io/docs/cloud/v6/#tag/Locations/operation/locationsGet). *Can't be used as `LocationConstraint` on bucket creation.*
func (o GetObjectStorageRegionResultOutput) Location() pulumi.StringOutput {
	return o.ApplyT(func(v GetObjectStorageRegionResult) string { return v.Location }).(pulumi.StringOutput)
}

// The available classes in the region
func (o GetObjectStorageRegionResultOutput) StorageClasses() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetObjectStorageRegionResult) []string { return v.StorageClasses }).(pulumi.StringArrayOutput)
}

// The version of the region properties
func (o GetObjectStorageRegionResultOutput) Version() pulumi.Float64Output {
	return o.ApplyT(func(v GetObjectStorageRegionResult) float64 { return v.Version }).(pulumi.Float64Output)
}

// The website URL for the region
func (o GetObjectStorageRegionResultOutput) Website() pulumi.StringOutput {
	return o.ApplyT(func(v GetObjectStorageRegionResult) string { return v.Website }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetObjectStorageRegionResultOutput{})
}
